name: Build

on:
  push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CREUSOT_VERSION: master

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone Creusot source
        run: |
          cd ..
          git clone https://github.com/creusot-rs/creusot --single-branch --branch $CREUSOT_VERSION

      - name: Build and test
        run: cargo test -Fsolutions

  creusot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0
          opam-pin: false

      - name: Clone Creusot source
        run: |
          cd ..
          git clone https://github.com/creusot-rs/creusot --single-branch --branch $CREUSOT_VERSION

      - name: Cache Creusot build
        uses: actions/cache@v4
        with:
          path: |
            creusot/target
            ~/.local/share/creusot
          key: ${{ runner.os }}

      - name: System dependencies
        run: |
          sudo apt update && sudo apt install opam libzmq3-dev
          opam init --bare
          opam --cli=2.1 var --global in-creusot-ci=true

      - name: Install Creusot
        run: |
          cd ../creusot
          ./INSTALL

      - name: Update registry
        run: cargo update --dry-run

      - name: Run Creusot
        run: cargo creusot -- -Fsolutions
